import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "061c20911f01"
down_revision = "0bcccf942e6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_sets", sa.Column("sub_id", sa.String(36), nullable=False)
    )  # UUIDを保存するための文字列
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_sets", "sub_id")
    # ### end Alembic commands ###
