"""add member num column

Revision ID: 0bcccf942e6f
Revises: 71a2242b8392
Create Date: 2024-10-06 03:55:35.927219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcccf942e6f'
down_revision: Union[str, None] = '71a2242b8392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('member_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'member_num')
    # ### end Alembic commands ###
