"""add played _at column

Revision ID: 71a2242b8392
Revises: 7fab0a136453
Create Date: 2024-10-04 06:17:57.987609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71a2242b8392"
down_revision: Union[str, None] = "7fab0a136453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("played_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "played_at")
    # ### end Alembic commands ###
