"""add description to quizset table

Revision ID: 7fab0a136453
Revises: 2c86ba545f1b
Create Date: 2024-09-20 07:52:08.729233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fab0a136453"
down_revision: Union[str, None] = "2c86ba545f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_sets", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_sets", "description")
    # ### end Alembic commands ###
