"""fix sub id

Revision ID: 80075120be14
Revises: 061c20911f01
Create Date: 2024-10-12 16:18:38.096684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80075120be14'
down_revision: Union[str, None] = '061c20911f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sets', 'sub_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sets', 'sub_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
