name: Push ECR

on:
  push:
    branches:
      - main

jobs:
    PushtoECR:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v3 
            
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-region: ap-northeast-1
                role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-ecr-user'

            - name: Login ECR
              run: |
                aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_ENDPOINT }}

            - name: Image Build & Push to ECR
              env:
                REPOSITORY_NAME: "i.maker"
                IMAGE_TAG: "${{ github.sha }}"
              run: |
                docker build --platform linux/x86_64 -t ${{ env.REPOSITORY_NAME }} .
                docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ secrets.AWS_ECR_ENDPOINT }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
                docker push ${{ secrets.AWS_ECR_ENDPOINT }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}